// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: Guid("10009af8-f2bb-4cf6-8594-f92d84e010dc")]
[assembly: CLSCompliant(true)]
[assembly: InternalsVisibleTo("Whisk")]
